# permissions for end users to edit eventingauths.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: eventingauth-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: eventing-auth-manager
    app.kubernetes.io/part-of: eventing-auth-manager
    app.kubernetes.io/managed-by: kustomize
  name: eventingauth-editor-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - eventingauths
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - eventingauths/status
  verbs:
  - get
